### ISSUE TITLE
frontコンテナでのエラーを突き止める

### ISSUE THREAD

**Issue by tomoyk** [cdsl-research/doktor-v2#53]
frontコンテナでの特定エンドポイント `GET /` で503が発生する．

https://github.com/cdsl-research/doktor-v2/blob/9d77ca2e337addd733bbdb88b998cdf4b921ac2b/front/main.py#L44-L78

Kubernetesのログでは以下が出力される．

```
koyama@doktor-stg1:~/doktor-v2/deploy/front$ k logs deployment.apps/front-app-deploy
Found 3 pods, using pod/front-app-deploy-d8c7f785-swfsp
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     10.42.0.0:33378 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
RuntimeError: coroutine raised StopIteration
```

**Comment by tomoyk** [comment]
二分探索で調べた結果，以下が怪しそう．

https://github.com/cdsl-research/doktor-v2/blob/9d77ca2e337addd733bbdb88b998cdf4b921ac2b/front/main.py#L55-L60

**Comment by tomoyk** [comment]
おそらく `nect(filter( ... ))` の内部でデータが見つからない場合にStopIterationが例外として発生していたと考えられる．

```
>>> next(filter(lambda x: x == 1, [2,3,4,5,6]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
>>> next(filter(lambda x: x == 1, [2,3,4,5,6,1]))
1
```

**Comment by tomoyk** [comment]
LGTM
